sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: b1D2AprVcNGYQhqpUHApjqr+RIpDh3vNML7NhkjIjq/Fq5nPz921HiyDidZmT2SG+Hd1artxJxosMXPfYvi6fUmOUwSmh83JpbMXhbI1D9/Y1InH4q9/5J4bgZFnGsCaZ6TMg9Fl9XtT41baUUQ7rpGr1UdJbWxsCEc6z458xvz6lwP5SGmbKth0D9eS0dgxAf1C2naMD4BWJ1HDCk+MpcctujLzpvcvYwIr0HKsbxbwsuFooJjAZQHehKLbQDOuW01i937nWMQrVzflKyCJaAz1dEmh0m+nwKhAhCJClVdxWwlINQ+3vBgysWEYlVnYm+Oh6MwhTZ5//s8mYgCZr8z3mr5dr0J64vBK0F+XrdakbEBjACiOfsSIewFdaT2ksz98q6tYQSZFHLrMSvd/kAJCLHgw3Q3tQEVVfo6SZ/oC4Zhf13mHBAHPT47eDGeZUQHCK+vh6FhFLwEJuF9HueJ+em+ivmf9Qj9Tt/9Rpv2JQbkSnH+0gg1ptA6qY9/eWXMPZNybZRHhbp/I1cMttawyDk2be5Tx+uSfkZ/lD1WuMz/T8gLxNuwWswV4lrwBS/rTY8FGVcnZP7hs6luzPcBye5VjzJzavdmfAF7rgBfLD5a3gRPbASY44T1KHZwDnXnDMl7+x6B6SPbx9oHEjmCFPFOTqKXL9DbQ3j0++0M=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/The-Case-of-the-Registered-Letter_1833
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy